"""Static market configuration: COMMODITIES, CONTRACT_SPECS, tuning constants.

Split out of commodity_dashboard.py — see CLAUDE.md "Architecture".
"""

import os
import csv
import contextlib
import io
import json
import re
import urllib.request
import urllib.parse
from datetime import date, datetime, time, timedelta
from dateutil.relativedelta import relativedelta

try:
    from zoneinfo import ZoneInfo
except ImportError:
    ZoneInfo = None

try:
    import yfinance as yf
except ImportError:
    yf = None  # The script warns and still generates HTML with placeholders

try:
    from curl_cffi import requests as curl_requests
except ImportError:
    curl_requests = None

try:
    from pypdf import PdfReader
except ImportError:
    PdfReader = None

__all__ = [
    'CBOT_AG_HOURS',
    'CME_ENERGY_HOURS',
    'CME_METALS_HOURS',
    'COMMODITIES',
    'CONTRACT_SPECS',
    'MONTH_CODES',
    'MONTH_NAMES',
    'SPREAD_MAX_GAP_DAYS',
    'SPREAD_SPIKE_REVERT_PCT',
    'YF_CONTRACT_LOOKAHEAD',
    'YF_EOD_BOARD_SETTLE_MIN_RATIO',
    'YF_EOD_SETTLE_READY_ET',
    'YF_LIQUID_ACTIVE_DAYS_AFTER_EXPIRY',
    'YF_LIQUID_ACTIVE_DAYS_BEFORE_EXPIRY',
    'YF_LIQUID_CONTINUOUS_EMPTY_STOP',
    'YF_LIQUID_CONTINUOUS_FORWARD_MONTHS',
    'YF_LIQUID_CONTINUOUS_LOOKBACK_MONTHS',
    'YF_LIQUID_CONTINUOUS_MAX_CONTRACTS',
    'YF_LIQUID_CONTINUOUS_MIN_VOLUME',
    'YF_TOTAL_VOLUME_EMPTY_STOP',
    'YF_TOTAL_VOLUME_FORWARD_MONTHS',
    'YF_TOTAL_VOLUME_LOOKAHEAD',
    'YF_TOTAL_VOLUME_LOOKBACK_MONTHS',
    'YF_TOTAL_VOLUME_MAX_CONTRACTS',
    'YF_TOTAL_VOLUME_MAX_POINTS',
    'YF_VOLUME_SUSPECT_LOOKBACK',
    'YF_VOLUME_SUSPECT_MIN_REFERENCE',
    'YF_VOLUME_SUSPECT_MIN_RUN',
    'YF_VOLUME_SUSPECT_RATIO',
    'YF_VOLUME_SUSPECT_RECENT_DAYS',
]



# ─────────────────────────────────────────────────────────────────────
#  DATA SOURCES
# ─────────────────────────────────────────────────────────────────────
#  Prices and contract data come from yfinance.
#  COT comes from the CFTC Public Reporting API.
#  Open Interest comes from CFTC only (weekly, via the COT report).
# ─────────────────────────────────────────────────────────────────────
YF_CONTRACT_LOOKAHEAD = 7  # no market trades more than 6 forward contracts; +1 buffer covers roll days. Far months only return empty Yahoo quotes.
YF_TOTAL_VOLUME_LOOKAHEAD = 18  # forward contracts to scan for legacy/cached volume paths
YF_TOTAL_VOLUME_LOOKBACK_MONTHS = 24  # enough to cover 12M charts plus stale data weekends/holidays
YF_TOTAL_VOLUME_FORWARD_MONTHS = 18   # include actively traded deferred months
YF_TOTAL_VOLUME_MAX_CONTRACTS = 64    # cap yfinance requests for dense monthly markets
YF_TOTAL_VOLUME_EMPTY_STOP = 8
YF_TOTAL_VOLUME_MAX_POINTS = 1300
YF_VOLUME_SUSPECT_LOOKBACK = 20
YF_VOLUME_SUSPECT_RATIO = 0.15
YF_VOLUME_SUSPECT_MIN_REFERENCE = 10000
YF_VOLUME_SUSPECT_MIN_RUN = 3
YF_VOLUME_SUSPECT_RECENT_DAYS = 420
YF_EOD_SETTLE_READY_ET = time(17, 30)  # a daily bar is only a settled EoD after this ET time (mirrors start.py)
YF_EOD_BOARD_SETTLE_MIN_RATIO = 0.5    # a market's final bar fixes the board-wide settled date only if its volume is >= this fraction of its recent norm
YF_LIQUID_CONTINUOUS_LOOKBACK_MONTHS = 12  # 12M covers the volume-led 6M/12M views; older single contracts are delisted at Yahoo, so the continuous fallback fills the rest (roll markers come from the expiry calendar)
YF_LIQUID_CONTINUOUS_FORWARD_MONTHS = 18
YF_LIQUID_CONTINUOUS_EMPTY_STOP = 24  # generous: don't let a block of missing old expiries abort the chain
YF_LIQUID_CONTINUOUS_MAX_CONTRACTS = 72
YF_LIQUID_CONTINUOUS_MIN_VOLUME = 1
YF_LIQUID_ACTIVE_DAYS_BEFORE_EXPIRY = 180
YF_LIQUID_ACTIVE_DAYS_AFTER_EXPIRY = 5
SPREAD_SPIKE_REVERT_PCT = 0.02       # drop a one-day calendar-spread value that spikes >this fraction of the front price and reverts next day
SPREAD_MAX_GAP_DAYS = 7              # keep only the most recent calendar-spread run without a gap larger than this (drops the sparse older backfill; Yahoo only serves the current contracts)


# ─────────────────────────────────────────────────────────────────────
#  FUTURES MONTH CODES (CME Standard)
# ─────────────────────────────────────────────────────────────────────
MONTH_CODES = {
    1: "F",  2: "G",  3: "H",  4: "J",   5: "K",  6: "M",
    7: "N",  8: "Q",  9: "U", 10: "V",  11: "X", 12: "Z",
}
MONTH_NAMES = {
    1: "Jan",  2: "Feb",  3: "Mar",  4: "Apr",   5: "May",  6: "Jun",
    7: "Jul",  8: "Aug",  9: "Sep", 10: "Oct",  11: "Nov", 12: "Dec",
}


# ─────────────────────────────────────────────────────────────────────
#  COMMODITY CONFIGURATION
# ─────────────────────────────────────────────────────────────────────
#  contract_months = actually tradable delivery months (real exchange cycles)
# ─────────────────────────────────────────────────────────────────────
COMMODITIES = {
    "wti_crude": {
        "display_name": "WTI Crude Oil",
        "category": "Energy",
        "tv_symbol": "NYMEX:CL1!",
        "yf_root": "CL",
        "yf_exchange": "NYM",
        "currency": "USD",
        "unit": "bbl",
        "tick_decimals": 2,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "067651",
        "yf_continuous": "CL=F",
    },
    "brent_crude": {
        "display_name": "Brent Crude Oil",
        "category": "Energy",
        "tv_symbol": "ICEEUR:BRN1!",
        "yf_root": "BZ",
        "yf_exchange": "NYM",
        "currency": "USD",
        "unit": "bbl",
        "tick_decimals": 2,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "06765T",
        "yf_continuous": "BZ=F",
    },
    "natural_gas": {
        "display_name": "Natural Gas (Henry Hub)",
        "category": "Energy",
        "tv_symbol": "NYMEX:NG1!",
        "yf_root": "NG",
        "yf_exchange": "NYM",
        "currency": "USD",
        "unit": "MMBtu",
        "tick_decimals": 3,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "023651",
        "yf_continuous": "NG=F",
    },
    "gold": {
        "display_name": "Gold",
        "category": "Metals",
        "tv_symbol": "COMEX:GC1!",
        "yf_root": "GC",
        "yf_exchange": "CMX",
        "currency": "USD",
        "unit": "troy oz",
        "tick_decimals": 1,
        "contract_months": [2, 4, 6, 8, 10, 12],  # G J M Q V Z
        "cftc_code": "088691",
        "yf_continuous": "GC=F",
    },
    "silver": {
        "display_name": "Silver",
        "category": "Metals",
        "tv_symbol": "COMEX:SI1!",
        "yf_root": "SI",
        "yf_exchange": "CMX",
        "currency": "USD",
        "unit": "troy oz",
        "tick_decimals": 3,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "084691",
        "yf_continuous": "SI=F",
    },
    "copper": {
        "display_name": "Copper",
        "category": "Metals",
        "tv_symbol": "COMEX:HG1!",
        "yf_root": "HG",
        "yf_exchange": "CMX",
        "currency": "USD",
        "unit": "lbs",
        "tick_decimals": 4,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "085692",
        "yf_continuous": "HG=F",
    },
    "platinum": {
        "display_name": "Platinum",
        "category": "Metals",
        "tv_symbol": "NYMEX:PL1!",
        "yf_root": "PL",
        "yf_exchange": "NYM",
        "currency": "USD",
        "unit": "troy oz",
        "tick_decimals": 1,
        "contract_months": [1, 4, 7, 10],  # F J N V
        "cftc_code": "076651",
        "yf_continuous": "PL=F",
    },
    "corn": {
        "display_name": "Corn",
        "category": "Agriculture",
        "tv_symbol": "CBOT:ZC1!",
        "yf_root": "ZC",
        "yf_exchange": "CBT",
        "currency": "USc",
        "unit": "bu",
        "tick_decimals": 2,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "002602",
        "yf_continuous": "ZC=F",
    },
    "wheat": {
        "display_name": "Wheat (Chicago SRW)",
        "category": "Agriculture",
        "tv_symbol": "CBOT:ZW1!",
        "yf_root": "ZW",
        "yf_exchange": "CBT",
        "currency": "USc",
        "unit": "bu",
        "tick_decimals": 2,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "001602",
        "yf_continuous": "ZW=F",
    },
    "soybeans": {
        "display_name": "Soybeans",
        "category": "Agriculture",
        "tv_symbol": "CBOT:ZS1!",
        "yf_root": "ZS",
        "yf_exchange": "CBT",
        "currency": "USc",
        "unit": "bu",
        "tick_decimals": 2,
        "contract_months": [1, 3, 5, 7, 8, 9, 11],  # F H K N Q U X
        "cftc_code": "005602",
        "yf_continuous": "ZS=F",
    },
    "soybean_oil": {
        "display_name": "Soybean Oil",
        "category": "Agriculture",
        "tv_symbol": "CBOT:ZL1!",
        "yf_root": "ZL",
        "yf_exchange": "CBT",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 2,
        "contract_months": [1, 3, 5, 7, 8, 9, 10, 12],  # F H K N Q U V Z
        "cftc_code": "007601",
        "yf_continuous": "ZL=F",
    },
    "sugar": {
        "display_name": "Sugar #11",
        "category": "Softs",
        "tv_symbol": "ICEUS:SB1!",
        "yf_root": "SB",
        "yf_exchange": "NYB",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 2,
        "contract_months": [3, 5, 7, 10],  # H K N V
        "cftc_code": "080732",
        "yf_continuous": "SB=F",
    },
    "coffee": {
        "display_name": "Coffee (Arabica)",
        "category": "Softs",
        "tv_symbol": "ICEUS:KC1!",
        "yf_root": "KC",
        "yf_exchange": "NYB",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 2,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "083731",
        "yf_continuous": "KC=F",
    },
    # ── Energy: Gasoline ──
    "gasoline": {
        "display_name": "RBOB Gasoline",
        "category": "Energy",
        "tv_symbol": "NYMEX:RB1!",
        "yf_root": "RB",
        "yf_exchange": "NYM",
        "currency": "USD",
        "unit": "gal",
        "tick_decimals": 4,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "111659",
        "yf_continuous": "RB=F",
    },
    # ── Softs: Cotton, OJ, Cocoa, Lumber ──
    "cotton": {
        "display_name": "Cotton #2",
        "category": "Softs",
        "tv_symbol": "ICEUS:CT1!",
        "yf_root": "CT",
        "yf_exchange": "NYB",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 2,
        "contract_months": [3, 5, 7, 10, 12],  # H K N V Z
        "cftc_code": "033661",
        "yf_continuous": "CT=F",
    },
    "orange_juice": {
        "display_name": "Orange Juice (FCOJ-A)",
        "category": "Softs",
        "tv_symbol": "ICEUS:OJ1!",
        "yf_root": "OJ",
        "yf_exchange": "NYB",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 2,
        "contract_months": [1, 3, 5, 7, 9, 11],  # F H K N U X
        "cftc_code": "040701",
        "yf_continuous": "OJ=F",
    },
    "cocoa": {
        "display_name": "Cocoa",
        "category": "Softs",
        "tv_symbol": "ICEUS:CC1!",
        "yf_root": "CC",
        "yf_exchange": "NYB",
        "currency": "USD",
        "unit": "metric ton",
        "tick_decimals": 0,
        "contract_months": [3, 5, 7, 9, 12],  # H K N U Z
        "cftc_code": "073732",
        "yf_continuous": "CC=F",
    },
    "lumber": {
        "display_name": "Lumber",
        "category": "Softs",
        "tv_symbol": "CME:LBR1!",
        "yf_root": "LBR",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "1000 board ft",
        "tick_decimals": 2,
        "contract_months": [1, 3, 5, 7, 9, 11],  # F H K N U X
        "cftc_code": "058644",
        "yf_continuous": "LBR=F",
    },
    # ── Livestock / Dairy ──
    "live_cattle": {
        "display_name": "Live Cattle",
        "category": "Livestock/Dairy",
        "tv_symbol": "CME:LE1!",
        "yf_root": "LE",
        "yf_exchange": "CME",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 3,
        "contract_months": [2, 4, 6, 8, 10, 12],  # G J M Q V Z
        "cftc_code": "057642",
        "yf_continuous": "LE=F",
    },
    "feeder_cattle": {
        "display_name": "Feeder Cattle",
        "category": "Livestock/Dairy",
        "tv_symbol": "CME:GF1!",
        "yf_root": "GF",
        "yf_exchange": "CME",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 3,
        "contract_months": [1, 3, 4, 5, 8, 9, 10, 11],  # F H J K Q U V X
        "cftc_code": "061641",
        "yf_continuous": "GF=F",
    },
    "lean_hogs": {
        "display_name": "Lean Hogs",
        "category": "Livestock/Dairy",
        "tv_symbol": "CME:HE1!",
        "yf_root": "HE",
        "yf_exchange": "CME",
        "currency": "USc",
        "unit": "lbs",
        "tick_decimals": 3,
        "contract_months": [2, 4, 5, 6, 7, 8, 10, 12],  # G J K M N Q V Z
        "cftc_code": "054642",
        "yf_continuous": "HE=F",
    },
    "class_iii_milk": {
        "display_name": "Class III Milk",
        "category": "Livestock/Dairy",
        "tv_symbol": "CME:DC1!",
        "yf_root": "DC",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "cwt",
        "tick_decimals": 2,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "052641",
        "yf_continuous": "DC=F",
    },
    # ── Indices ──
    "es_sp500": {
        "display_name": "E-mini S&P 500",
        "category": "Indices",
        "tv_symbol": "CME_MINI:ES1!",
        "yf_root": "ES",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "index pts",
        "tick_decimals": 2,
        "contract_months": [3, 6, 9, 12],  # H M U Z
        "cftc_code": "13874A",
        "yf_continuous": "ES=F",
    },
    "nq_nasdaq": {
        "display_name": "E-mini Nasdaq 100",
        "category": "Indices",
        "tv_symbol": "CME_MINI:NQ1!",
        "yf_root": "NQ",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "index pts",
        "tick_decimals": 2,
        "contract_months": [3, 6, 9, 12],  # H M U Z
        "cftc_code": "209742",
        "yf_continuous": "NQ=F",
    },
    "ym_dow": {
        "display_name": "E-mini Dow ($5)",
        "category": "Indices",
        "tv_symbol": "CBOT_MINI:YM1!",
        "yf_root": "YM",
        "yf_exchange": "CBT",
        "currency": "USD",
        "unit": "index pts",
        "tick_decimals": 0,
        "contract_months": [3, 6, 9, 12],  # H M U Z
        "cftc_code": "124603",
        "yf_continuous": "YM=F",
    },
    "rty_russell": {
        "display_name": "E-mini Russell 2000",
        "category": "Indices",
        "tv_symbol": "CME_MINI:RTY1!",
        "yf_root": "RTY",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "index pts",
        "tick_decimals": 2,
        "contract_months": [3, 6, 9, 12],  # H M U Z
        "cftc_code": "239742",
        "yf_continuous": "RTY=F",
    },
    # ── Currencies ──
    "usdx": {
        "display_name": "US Dollar Index",
        "category": "Currencies",
        "tv_symbol": "ICEUS:DX1!",
        "yf_root": "DX",
        "yf_exchange": "NYB",
        "currency": "USD",
        "unit": "index pts",
        "tick_decimals": 3,
        "contract_months": [3, 6, 9, 12],  # H M U Z
        "cftc_code": "098662",
        "yf_continuous": "DX-Y.NYB",
        "chart_format": "dxy_index_proxy",
        "chart_label": "US Dollar Index (DXY)",
        "chart_method": "Yahoo Finance US Dollar Index cash/index proxy",
        "risk_symbol": "DX-Y.NYB",
        "risk_role": "usd_index",
    },
    "eur_fx": {
        "display_name": "Euro FX",
        "category": "Currencies",
        "tv_symbol": "CME:6E1!",
        "yf_root": "6E",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per EUR",
        "tick_decimals": 5,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "099741",
        "yf_continuous": "6E=F",
    },
    "gbp_fx": {
        "display_name": "British Pound",
        "category": "Currencies",
        "tv_symbol": "CME:6B1!",
        "yf_root": "6B",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per GBP",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "096742",
        "yf_continuous": "6B=F",
    },
    "cad_fx": {
        "display_name": "Canadian Dollar",
        "category": "Currencies",
        "tv_symbol": "CME:6C1!",
        "yf_root": "6C",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per CAD",
        "tick_decimals": 5,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "090741",
        "yf_continuous": "6C=F",
    },
    "jpy_fx": {
        "display_name": "Japanese Yen",
        "category": "Currencies",
        "tv_symbol": "CME:6J1!",
        "yf_root": "6J",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per JPY",
        "tick_decimals": 7,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "097741",
        "yf_continuous": "6J=F",
    },
    "chf_fx": {
        "display_name": "Swiss Franc",
        "category": "Currencies",
        "tv_symbol": "CME:6S1!",
        "yf_root": "6S",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per CHF",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "092741",
        "yf_continuous": "6S=F",
    },
    "aud_fx": {
        "display_name": "Australian Dollar",
        "category": "Currencies",
        "tv_symbol": "CME:6A1!",
        "yf_root": "6A",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per AUD",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "232741",
        "yf_continuous": "6A=F",
    },
    "nzd_fx": {
        "display_name": "New Zealand Dollar",
        "category": "Currencies",
        "tv_symbol": "CME:6N1!",
        "yf_root": "6N",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per NZD",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "112741",
        "yf_continuous": "6N=F",
    },
    # ── Bonds / Rates ──
    "zb_tbond": {
        "display_name": "30-Year U.S. T-Bond",
        "category": "Bonds",
        "tv_symbol": "CBOT:ZB1!",
        "yf_root": "ZB",
        "yf_exchange": "CBT",
        "currency": "USD",
        "unit": "pts (1/32)",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "020601",
        "yf_continuous": "ZB=F",
    },
    "zn_10y": {
        "display_name": "10-Year U.S. T-Note",
        "category": "Bonds",
        "tv_symbol": "CBOT:ZN1!",
        "yf_root": "ZN",
        "yf_exchange": "CBT",
        "currency": "USD",
        "unit": "pts (1/32)",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "043602",
        "yf_continuous": "ZN=F",
    },
    "zf_5y": {
        "display_name": "5-Year U.S. T-Note",
        "category": "Bonds",
        "tv_symbol": "CBOT:ZF1!",
        "yf_root": "ZF",
        "yf_exchange": "CBT",
        "currency": "USD",
        "unit": "pts (1/128)",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "044601",
        "yf_continuous": "ZF=F",
    },
    "zt_2y": {
        "display_name": "2-Year U.S. T-Note",
        "category": "Bonds",
        "tv_symbol": "CBOT:ZT1!",
        "yf_root": "ZT",
        "yf_exchange": "CBT",
        "currency": "USD",
        "unit": "pts (1/128)",
        "tick_decimals": 4,
        "contract_months": [3, 6, 9, 12],
        "cftc_code": "042601",
        "yf_continuous": "ZT=F",
    },
    "bitcoin": {
        "display_name": "Bitcoin",
        "category": "Crypto",
        "tv_symbol": "CME:BTC1!",
        "yf_root": "BTC",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per BTC",
        "tick_decimals": 2,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "133741",
        "yf_continuous": "BTC=F",
    },
    "ethereum": {
        "display_name": "Ethereum",
        "category": "Crypto",
        "tv_symbol": "CME:ETH1!",
        "yf_root": "ETH",
        "yf_exchange": "CME",
        "currency": "USD",
        "unit": "per ETH",
        "tick_decimals": 2,
        "contract_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "cftc_code": "146021",
        "yf_continuous": "ETH=F",
    },
}

# ─────────────────────────────────────────────────────────────────────
#  CONTRACT SPECIFICATIONS
# ─────────────────────────────────────────────────────────────────────
CME_ENERGY_HOURS = "CME Globex: Sun-Fri 18:00-17:00 ET, daily pause 17:00-18:00 ET"
CME_METALS_HOURS = "CME Globex: Sun-Fri 18:00-17:00 ET, daily pause 17:00-18:00 ET"
CBOT_AG_HOURS = "CME Globex: Sun-Fri 20:00-08:45 ET and Mon-Fri 09:30-14:20 ET"

CONTRACT_SPECS = {
    "wti_crude": {
        "exchange": "NYMEX / CME",
        "tick": "$0.01 per bbl = $10.00 per contract",
        "contract_size": "1,000 barrels",
        "expiration": "3 business days before the 25th calendar day of the month before the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_25th_prev_month", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "brent_crude": {
        "exchange": "ICE Futures Europe",
        "tick": "$0.01 per bbl = $10.00 per contract",
        "contract_size": "1,000 barrels",
        "expiration": "Last business day of the second month before the contract month",
        "trading_hours": "ICE: New York 20:00-18:00 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/219/BrentCrude-Futures",
        "expiry_rule": {"kind": "last_bd_of_prev_month", "params": {"k": 2}},
        "hours_session": {"start": "01:00", "end": "23:00", "tz": "Europe/London", "note": "ICE London"},
    },
    "natural_gas": {
        "exchange": "NYMEX / CME",
        "tick": "$0.001 per MMBtu = $10.00 per contract",
        "contract_size": "10,000 MMBtu",
        "expiration": "3 business days before the first calendar day of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/energy/natural-gas/natural-gas.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_1st_of_delivery", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "gold": {
        "exchange": "COMEX / CME",
        "tick": "$0.10 per troy oz = $10.00 per contract",
        "contract_size": "100 troy ounces",
        "expiration": "Third-to-last business day of the delivery month",
        "trading_hours": CME_METALS_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/metals/precious/gold.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "silver": {
        "exchange": "COMEX / CME",
        "tick": "$0.005 per troy oz = $25.00 per contract",
        "contract_size": "5,000 troy ounces",
        "expiration": "Third-to-last business day of the contract month",
        "trading_hours": CME_METALS_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/metals/precious/silver.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "copper": {
        "exchange": "COMEX / CME",
        "tick": "$0.0005 per lb = $12.50 per contract",
        "contract_size": "25,000 pounds",
        "expiration": "Third-to-last business day of the contract month",
        "trading_hours": CME_METALS_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/metals/base/copper.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "platinum": {
        "exchange": "NYMEX / CME",
        "tick": "$0.10 per troy oz = $5.00 per contract",
        "contract_size": "50 troy ounces",
        "expiration": "Third-to-last business day of the contract month",
        "trading_hours": CME_METALS_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/metals/precious/platinum.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "corn": {
        "exchange": "CBOT / CME",
        "tick": "0.25 US cents per bu = $12.50 per contract",
        "contract_size": "5,000 bushels",
        "expiration": "Business day before the 15th calendar day of the contract month",
        "trading_hours": CBOT_AG_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/grains/corn.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_15th_of_delivery", "params": {}},
        "hours_session": {"start": "19:00", "end": "13:20", "tz": "America/Chicago", "note": "Sun-Fri 19:00 + Mon-Fri 08:30-13:20 CT"},
    },
    "wheat": {
        "exchange": "CBOT / CME",
        "tick": "0.25 US cents per bu = $12.50 per contract",
        "contract_size": "5,000 bushels",
        "expiration": "Business day before the 15th calendar day of the contract month; expiring contracts close at 13:00 ET",
        "trading_hours": CBOT_AG_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/grains/wheat.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_15th_of_delivery", "params": {}},
        "hours_session": {"start": "19:00", "end": "13:20", "tz": "America/Chicago", "note": "Sun-Fri 19:00 + Mon-Fri 08:30-13:20 CT"},
    },
    "soybeans": {
        "exchange": "CBOT / CME",
        "tick": "0.25 US cents per bu = $12.50 per contract",
        "contract_size": "5,000 bushels",
        "expiration": "Business day before the 15th calendar day of the contract month; expiring contracts close at 13:00 ET",
        "trading_hours": CBOT_AG_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/oilseeds/soybean.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_15th_of_delivery", "params": {}},
        "hours_session": {"start": "19:00", "end": "13:20", "tz": "America/Chicago", "note": "Sun-Fri 19:00 + Mon-Fri 08:30-13:20 CT"},
    },
    "soybean_oil": {
        "exchange": "CBOT / CME",
        "tick": "0.01 US cents per lb = $6.00 per contract",
        "contract_size": "60,000 pounds",
        "expiration": "Business day before the 15th calendar day of the contract month; expiring contracts close at 13:00 ET",
        "trading_hours": CBOT_AG_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/oilseeds/soybean-oil.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_15th_of_delivery", "params": {}},
        "hours_session": {"start": "19:00", "end": "13:20", "tz": "America/Chicago", "note": "Sun-Fri 19:00 + Mon-Fri 08:30-13:20 CT"},
    },
    "sugar": {
        "exchange": "ICE Futures U.S.",
        "tick": "0.01 US cents per lb = $11.20 per contract",
        "contract_size": "112,000 pounds",
        "expiration": "Last business day of the month before the delivery month",
        "trading_hours": "ICE: New York 03:30-13:00 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/23/sugar-no-11-futures",
        "expiry_rule": {"kind": "last_bd_of_prev_month", "params": {"k": 1}},
        "hours_session": {"start": "03:30", "end": "13:00", "tz": "America/New_York", "note": "ICE New York"},
    },
    "coffee": {
        "exchange": "ICE Futures U.S.",
        "tick": "0.05 US cents per lb = $18.75 per contract",
        "contract_size": "37,500 pounds",
        "expiration": "One business day before Last Notice Day; LND is 7 business days before month-end",
        "trading_hours": "ICE: New York 04:15-13:30 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/15/Coffee-C-Futures/specs",
        "expiry_rule": {"kind": "bd_before_last_notice", "params": {"bd_before_eom": 7}},
        "hours_session": {"start": "04:15", "end": "13:30", "tz": "America/New_York", "note": "ICE New York"},
    },
    "gasoline": {
        "exchange": "NYMEX / CME",
        "tick": "$0.0001 per gal = $4.20 per contract",
        "contract_size": "42,000 gallons",
        "expiration": "Last business day of the month before the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/energy/refined-products/rbob-gasoline.contractSpecs.html",
        "expiry_rule": {"kind": "last_bd_of_prev_month", "params": {"k": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "Sun-Fri, pause 16:00-17:00 CT"},
    },
    "cotton": {
        "exchange": "ICE Futures U.S.",
        "tick": "0.01 US cents per lb = $5.00 per contract",
        "contract_size": "50,000 pounds",
        "expiration": "Business day before 5 business days before month-end (Last Trading Day)",
        "trading_hours": "ICE: New York 21:00-14:20 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/254/Cotton-No-2-Futures",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 6}},
        "hours_session": {"start": "21:00", "end": "14:20", "tz": "America/New_York", "note": "ICE New York"},
    },
    "orange_juice": {
        "exchange": "ICE Futures U.S.",
        "tick": "0.05 US cents per lb = $7.50 per contract",
        "contract_size": "15,000 pounds",
        "expiration": "14th business day before month-end of the delivery month",
        "trading_hours": "ICE: New York 08:00-14:00 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/30/FCOJ-A-Futures",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 14}},
        "hours_session": {"start": "08:00", "end": "14:00", "tz": "America/New_York", "note": "ICE New York"},
    },
    "cocoa": {
        "exchange": "ICE Futures U.S.",
        "tick": "$1 per metric ton = $10.00 per contract",
        "contract_size": "10 metric tons",
        "expiration": "Eleventh business day before the last business day of the delivery month",
        "trading_hours": "ICE: New York 04:45-13:30 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/7/Cocoa-Futures",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 11}},
        "hours_session": {"start": "04:45", "end": "13:30", "tz": "America/New_York", "note": "ICE New York"},
    },
    "lumber": {
        "exchange": "CME",
        "tick": "$0.50 per 1000 bf = $55.00 per contract",
        "contract_size": "27,500 board feet",
        "expiration": "Business day before the 16th calendar day of the delivery month",
        "trading_hours": "CME Globex: Mon-Fri 10:00-14:55 ET",
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/lumber-and-softs/lumber.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_15th_of_delivery", "params": {}},
        "hours_session": {"start": "09:00", "end": "13:55", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "live_cattle": {
        "exchange": "CME",
        "tick": "$0.00025 per lb = $10.00 per contract",
        "contract_size": "40,000 pounds",
        "expiration": "Last business day of the delivery month",
        "trading_hours": "CME Globex: Mon-Fri 09:30-14:05 ET",
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/livestock/live-cattle.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "08:30", "end": "13:05", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "feeder_cattle": {
        "exchange": "CME",
        "tick": "$0.00025 per lb = $12.50 per contract",
        "contract_size": "50,000 pounds",
        "expiration": "Last Thursday of the delivery month (with exceptions)",
        "trading_hours": "CME Globex: Mon-Fri 09:30-14:05 ET",
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/livestock/feeder-cattle.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "08:30", "end": "13:05", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "lean_hogs": {
        "exchange": "CME",
        "tick": "$0.00025 per lb = $10.00 per contract",
        "contract_size": "40,000 pounds",
        "expiration": "10th business day of the delivery month",
        "trading_hours": "CME Globex: Mon-Fri 09:30-14:05 ET",
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/livestock/lean-hogs.contractSpecs.html",
        "expiry_rule": {"kind": "nth_bd_of_delivery", "params": {"n": 10}},
        "hours_session": {"start": "08:30", "end": "13:05", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "class_iii_milk": {
        "exchange": "CME",
        "tick": "$0.01 per cwt = $20.00 per contract",
        "contract_size": "200,000 pounds",
        "expiration": "Business day after the USDA price release (approx. 5th business day of the following month)",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/agriculture/dairy/class-iii-milk.contractSpecs.html",
        "expiry_rule": {"kind": "last_bd_of_prev_month", "params": {"k": 0}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "es_sp500": {
        "exchange": "CME",
        "tick": "0.25 index pts = $12.50 per contract",
        "contract_size": "$50 × S&P 500 Index",
        "expiration": "Third Friday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/equity-index/us-index/e-mini-sandp500.contractSpecs.html",
        "expiry_rule": {"kind": "nth_weekday_of_delivery", "params": {"weekday": 4, "n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "nq_nasdaq": {
        "exchange": "CME",
        "tick": "0.25 index pts = $5.00 per contract",
        "contract_size": "$20 × Nasdaq-100 Index",
        "expiration": "Third Friday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/equity-index/us-index/e-mini-nasdaq-100.contractSpecs.html",
        "expiry_rule": {"kind": "nth_weekday_of_delivery", "params": {"weekday": 4, "n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "ym_dow": {
        "exchange": "CBOT / CME",
        "tick": "1 index pt = $5.00 per contract",
        "contract_size": "$5 × Dow Jones Industrial Average",
        "expiration": "Third Friday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/equity-index/us-index/e-mini-dow.contractSpecs.html",
        "expiry_rule": {"kind": "nth_weekday_of_delivery", "params": {"weekday": 4, "n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "rty_russell": {
        "exchange": "CME",
        "tick": "0.10 index pts = $5.00 per contract",
        "contract_size": "$50 × Russell 2000 Index",
        "expiration": "Third Friday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/equity-index/us-index/e-mini-russell-2000.contractSpecs.html",
        "expiry_rule": {"kind": "nth_weekday_of_delivery", "params": {"weekday": 4, "n": 3}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "usdx": {
        "exchange": "ICE Futures U.S.",
        "tick": "0.005 index pts = $5.00 per contract",
        "contract_size": "$1.000 × Index",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": "ICE: Sun-Fri 20:00-17:00 ET, daily pause 17:00-20:00 ET",
        "source": "ICE",
        "source_url": "https://www.ice.com/products/194/US-Dollar-Index-Futures",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "20:00", "end": "17:00", "tz": "America/New_York", "note": "ICE, nearly 24h"},
    },
    "eur_fx": {
        "exchange": "CME",
        "tick": "0.00005 = $6.25 per contract",
        "contract_size": "125,000 EUR",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/euro-fx.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "gbp_fx": {
        "exchange": "CME",
        "tick": "0.0001 = $6.25 per contract",
        "contract_size": "62,500 GBP",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/british-pound.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "cad_fx": {
        "exchange": "CME",
        "tick": "0.00005 = $5.00 per contract",
        "contract_size": "100,000 CAD",
        "expiration": "Business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/canadian-dollar.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "jpy_fx": {
        "exchange": "CME",
        "tick": "0.0000005 = $6.25 per contract",
        "contract_size": "12,500,000 JPY",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/japanese-yen.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "chf_fx": {
        "exchange": "CME",
        "tick": "0.0001 = $12.50 per contract",
        "contract_size": "125,000 CHF",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/swiss-franc.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "aud_fx": {
        "exchange": "CME",
        "tick": "0.0001 = $10.00 per contract",
        "contract_size": "100,000 AUD",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/australian-dollar.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "nzd_fx": {
        "exchange": "CME",
        "tick": "0.0001 = $10.00 per contract",
        "contract_size": "100,000 NZD",
        "expiration": "Second business day before the third Wednesday of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/fx/g10/new-zealand-dollar.contractSpecs.html",
        "expiry_rule": {"kind": "bd_before_third_wednesday", "params": {"n": 2}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "zb_tbond": {
        "exchange": "CBOT / CME",
        "tick": "1/32 of a point = $31.25 per contract",
        "contract_size": "$100,000 face value",
        "expiration": "7th business day before the last business day of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/interest-rates/us-treasury/30-year-us-treasury-bond.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 7}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "zn_10y": {
        "exchange": "CBOT / CME",
        "tick": "1/64 of a point = $15.625 per contract",
        "contract_size": "$100,000 face value",
        "expiration": "7th business day before the last business day of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/interest-rates/us-treasury/10-year-us-treasury-note.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 7}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "zf_5y": {
        "exchange": "CBOT / CME",
        "tick": "1/128 of a point = $7.8125 per contract",
        "contract_size": "$100,000 face value",
        "expiration": "Last business day of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/interest-rates/us-treasury/5-year-us-treasury-note.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "zt_2y": {
        "exchange": "CBOT / CME",
        "tick": "1/128 of a point = $7.8125 per contract",
        "contract_size": "$200,000 face value",
        "expiration": "Last business day of the delivery month",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/interest-rates/us-treasury/2-year-us-treasury-note.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "bitcoin": {
        "exchange": "CME",
        "tick": "$5.00 per bitcoin = $25.00 per contract",
        "contract_size": "5 bitcoin",
        "expiration": "Last Friday of the contract month (cash-settled to the CME CF Bitcoin Reference Rate)",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/cryptocurrencies/bitcoin/bitcoin.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
    "ethereum": {
        "exchange": "CME",
        "tick": "$0.05 per ether = $2.50 per contract",
        "contract_size": "50 ether",
        "expiration": "Last Friday of the contract month (cash-settled to the CME CF Ether-Dollar Reference Rate)",
        "trading_hours": CME_ENERGY_HOURS,
        "source": "CME",
        "source_url": "https://www.cmegroup.com/markets/cryptocurrencies/ether/ether.contractSpecs.html",
        "expiry_rule": {"kind": "nth_last_bd_of_delivery", "params": {"n": 1}},
        "hours_session": {"start": "17:00", "end": "16:00", "tz": "America/Chicago", "note": "CME Globex"},
    },
}
